### ISSUE TITLE
What is the purpose of the thirdparty directory?

### ISSUE THREAD

**Issue by MakisH** [precice/openfast-adapter#1]
I currently only see a copy of the Apache 2.0 license there. Was this directory meant to include anything else?

**Comment by uekerman** [comment]
One probably has to put the Apache license somewhere, see [comment in README](https://github.com/precice/openfast-adapter?tab=readme-ov-file#license-and-attribution). What would be a standard location for this?

**Comment by MakisH** [comment]
The license is typically placed on the root directory, and there is an LGPL copy in that: https://github.com/precice/openfast-adapter/blob/main/LICENSE

The `thirdparty/` directory typically includes external libraries and other assets, but there are currently none. That's why I was wondering.

**Comment by uekerman** [comment]
> The license is typically placed on the root directory, and there is an LGPL copy in that: https://github.com/precice/openfast-adapter/blob/main/LICENSE

Yes, this is the license of this code. But it is based on a different code, which was Apache 2.0, so we need to put that license somewhere. Understandable what I mean?

**Comment by MakisH** [comment]
I see. Then I have some questions/comments:

1. Is LGPL v2.1 compatible with Apache 2v? I have no idea, but I am wondering why [this figure](https://web.archive.org/web/20210101030518/https://dwheeler.com/essays/floss-license-slide.html) is only pointing from Apache to LGPL v3.
2. Why using a different license for the adapter? We so far had the unofficial policy of using the same license as the solver. We can also extend that to "compatible license" (good time to make a decision about the policy).
3. To what extent was code reused?
4. Would it be clearer if a license statement was at the beginning of the respective code files, potentially redirecting to `thirdparty/` for a copy of the license?
5. The purpose of `thirdparty/` could be more specific in the README and, if this needs to stay, I would expect a `thirdparty/README.md` explaining what this license is for.

**Comment by uekerman** [comment]
> but I am wondering why [this figure](https://web.archive.org/web/20210101030518/https://dwheeler.com/essays/floss-license-slide.html) is only pointing from Apache to LGPL v3.

I think the arrow points in the direction that we need. Makes also sense to me. Apache is "weaker" than LGPL, so you can use Apache things in an LGPL code, but not the other way around.

**Comment by LeonardWilleke** [comment]
To answer some of the questions from @MakisH

**Comment by LeonardWilleke** [comment]
Some answers on the comments from @MakisH 

> To what extent was code reused?
Three helper functions to read yaml input files (100 lines of code) were used from an existing example OpenFAST API example. The example is part of 
> ... I would expect a thirdparty/README.md explaining what this license is for
I added a short README.md in `thirdparty` explaining to what extend code was reused and why the license is there
