### ISSUE TITLE
When compiling the following error, how to solve it

### ISSUE THREAD

**Issue by Xichenye** [precice/openfast-adapter#10]
When compiling the following error, how to solve it
![image](https://github.com/user-attachments/assets/96e90aa5-593e-423a-a38a-6e6c290b7e59)

**Comment by MakisH** [comment]
Hi @Xichenye,

you first need to get and build OpenFAST itself, with the C++ API, and make it discoverable in your system. See the README: https://github.com/precice/openfast-adapter/blob/main/README.md

Please ask questions in the preCICE forum, as the issues are meant for bug reports and feature requests: https://precice.discourse.group/
